name: Build and Package

on:
  push:
    tags:
      - 'v*' # 在推送符合 v* 格式的标签时触发
  workflow_dispatch: # 允许手动触发

env:
  TMP_DIR = "tmp"
  DIST_DIR = "dist"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary
        run: make build-all

      - name: Prepare upload file
        run: |
          mkdir "$DIST_DIR"
          for file in "$TMP_DIR"/*; do
            if [ -f "$file" ]; then
              zip -r "$DIST_DIR/${file%.*}".zip assets/ config.toml $file
            fi
          done
          cp "$TMP_DIR"/* "$DIST_DIR"/

      - name: Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          generate_release_notes: true
          draft: 'true'
          artifacts: "$DIST_DIR/*"


