name: Build and Release

on:
  push:
    tags:
      - 'v*' # 在推送符合 v* 格式的标签时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary
        run: make build-all

      - name: Prepare upload file
        run: |
          for file in tmp/*; do
            if [ -f "$file" ]; then
              echo "$file"
              if [[ $file == *"windows"* ]]; then
                zip -r "${file%.*}".zip assets/ *.toml
                zip -r "${file%.*}".zip $file -j
              else
                tar -czf "${file%.*}".tar.gz assets/ *.toml -C tmp "$(basename "$file")"
              fi
            fi
          done
          mv *.toml tmp/
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: tmp/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}